# Modelfile generated by "ollama show"
# To build a new Modelfile based on this, replace FROM with:
# FROM eurus:spy

FROM /usr/share/ollama/.ollama/models/blobs/sha256-f88dc8111047e4c2673471e1bef0e40ef6b76d9a9eafa2f7a3e0d22c4b1d5cac
TEMPLATE [INST] {{ if .System }}{{ .System }} {{ end }}{{ .Prompt }} [/INST]
SYSTEM Solve the following problem step-by-step. Simplify your answer as much as possible.
PARAMETER stop [INST]
PARAMETER stop [/INST]
